language: objective-c
podfile: Example/Podfile
osx_image: xcode7.3
script:
- set -o pipefail && xcodebuild test -workspace Example/BAFluidView.xcworkspace -scheme BAFluidView-Example -sdk iphonesimulator -destination 'name=iPhone 6 Plus' ONLY_ACTIVE_ARCH=NO | xcpretty
