# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.105.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    
    carthage
  end
  
  desc "Responsible for building and signing the app"
  private_lane :build_app do |options|
    # Download the provisioning profile for the app
    sigh(output_path: "./fastlane/profiles") # Distribution Profile
  
    # Download the provisioning profile
    sigh(
      output_path: "./fastlane/profiles",
      app_identifier: "com.theoven.H2O"
    )
  
    increment_build_number # version bump
  
    gym(
      project: "H2O.xcodeproj",
      scheme: "Release",
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  
  lane :beta do
    build_app
  
    pilot
  
    commit_version_bump(
      message: 'Build Version Bump by fastlane',
      force: true
    )
  
    build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    add_git_tag(tag: "testflight-#{build_number}")
  
    push_to_git_remote

    slack(
       message: "Successfully deployed new Testflight Beta Update."
     )
  
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "H2O") # Build your app - more options available
    deliver(force: true)

    slack(
       message: "Successfully deployed new App Update."
     )
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

  end

  error do |lane, exception|
    slack(
       message: exception.message,
       success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
